import {Metadata} from "next";
import {Menu} from "@/components/menu/server-menu/Menu";
import {Search} from "@/components/search/Search";
import "./globals.css";
import React from "react";


// const geistSans = Geist({
//     variable: "--font-geist-sans",
//     subsets: ["latin"],
// });
//
// const geistMono = Geist_Mono({
//     variable: "--font-geist-mono",
//     subsets: ["latin"],
// });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body>
        <Menu/>
        <Search/>
        {children}
        <hr/>
        </body>
        </html>
    );
}